/**
 * Cloudflare Pages SSR Entry Point — Remix v2
 *
 * This file is the Cloudflare Pages Function that handles every request.
 * It imports the Remix server build and delegates all routing to it.
 *
 * Architecture:
 *   - Remix builds the server bundle into `build/server/index.js`
 *   - This Function imports that bundle and creates a fetch handler
 *   - Cloudflare Pages routes all requests through this Function
 */
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build is generated by remix vite:build
import * as build from "../build/server/index.js";

export const onRequest = createPagesFunctionHandler({ build });